### ISSUE TITLE
noti: 답장 또는 읽기 처리시 pending 유지

### ISSUE THREAD

**Issue by naijun0403** [nunnu1028/new-banced#12]
## Environment
OS: Android 11
Banced Version: 1.2.5

## reproduce bug
1. 상태바에 카카오톡 알림이 옵니다.
2. 이떄, 더보기 화살표를 눌러서 읽기, 답장 버튼이 나오게 합니다.
3. 답장을 눌러 아무 메세지를 보내려 시도합니다.
4. 이때 pending 상태가 유지되며, 요청이 처리되지 않습니다.

**Comment by nunnu1028** [comment]
[release](https://github.com/nunnu1028/new-banced/releases/tag/1.2.6)
