### ISSUE TITLE
삭제 오류

### ISSUE THREAD

**Issue by TianaJ3** [nunnu1028/new-banced#9]
이모티콘과 채팅을 같이 보낸메세지를 삭제하면 오류, 카카오톡 프로필보낸거 삭제하면 오류, 사진 삭제하면 오류, 이거 말고도 더 많은데 9.9.0은 좀 나아지길

**Comment by TianaJ3** [comment]
> 이모티콘과 채팅을 같이 보낸메세지를 삭제하면 오류남 + 카카오톡 프로필보낸거 삭제하면 오류, 이거 말고도 더 많은데 고칠부분이 많은듯

**Comment by nunnu1028** [comment]
[release](https://github.com/nunnu1028/new-banced/releases/tag/1.2.0)
